"""WHICH HULLS MAY BE USED FOR WHAT — the permanent population identity.

M6/M8 (operator brief SS12-SS14). A ">= 95% unattended" claim is only
meaningful against a population that (a) can be named exactly, (b) can be
regenerated, and (c) was never tuned against. None of the three held before
this module existed.

MEASURED 2026-08-20, and this is why the identity is not just the seed:

    bank                              seed  n   stream
    gate2u-n74-mesh.json                 0  74  15-gene
    gate2u-cap7-mesh.json                0  25  15-gene  (prefix of n74)
    gate2u-postfix-backoff-mesh.json     0  25  15-gene  (prefix of n74)
    gate2u-campaign-baseline.json        0  20  15-gene  (prefix of n74)
    gate2u-16gene-mesh.json              0  25  16-gene
    gate2u-16gene-mesh-161stl.json       0  25  16-gene  (prefix)
    gate2u-16gene-solve.json             0  18  16-gene  (prefix)

Every one records `seed = 0`, and the two streams share **ZERO** hulls --
verified by comparing waterline lengths, 0 of 25 in common and 0 as a set.
`sample_valid` draws from `default_rng(seed)`, so ADDING A GENE CHANGES THE
DRAW SEQUENCE and the same seed names a different population. `seed = 0` is
therefore not an identity; `(arity, seed)` is.

THE CONSEQUENCE IS NOT COSMETIC. The current grammar arity is 16, so the
74-hull bank -- the largest evidence base in this repository -- is drawn from
a 15-gene grammar that no longer exists and **cannot be regenerated by the
current code**. Any percentage quoted from it has a denominator today's code
cannot reconstruct. That is the same defect class as a ledger watermark
citing a deleted run directory (gap N6), applied to a population instead of
to a directory.

It is also exactly what six of the suite's eighteen skips have been saying:
"the screen's bars were calibrated on a 15-parameter genome and this tree
has 16; the campaign labels cannot be transferred."
"""
from __future__ import annotations

#: The grammar arity a population was drawn at. Part of the identity, NOT
#: metadata: two populations with the same seed and different arity share no
#: hulls. Read from `grammar.LOW` at write time; never hard-code a bank's.
def current_arity() -> int:
    from . import grammar
    return len(grammar.LOW)


#: EVERY tuning artifact in this repository to date draws from seed 0, at one
#: arity or the other. Seed 0 is therefore DEVELOPMENT for good: it is where
#: rules were discovered, bars were calibrated and thresholds were moved, and
#: contamination is a ONE-WAY DOOR. No amount of later care makes a hull that
#: shaped a bar into evidence about that bar.
DEV_SEED = 0

#: Never used to tune. Drawn for measuring a model that is already fixed.
VAL_SEED = 20260820

#: Opened ONCE, for the final Gate 2U claim, with the rules frozen before it
#: is drawn. If it is used twice it is a validation set, not a held-out one.
HOLDOUT_SEED = 20260821

SPLIT_DEV = "dev"
SPLIT_VAL = "validation"
SPLIT_HOLDOUT = "held-out"
SPLIT_UNKNOWN = "UNKNOWN"

_BY_SEED = {DEV_SEED: SPLIT_DEV, VAL_SEED: SPLIT_VAL,
            HOLDOUT_SEED: SPLIT_HOLDOUT}


def split_of_seed(seed) -> str:
    """Which split a seed belongs to.

    An unrecognised seed is SPLIT_UNKNOWN and that is NOT a synonym for
    'dev'. A population nobody declared is a population nobody can reason
    about, and calling it development would silently license quoting it.
    """
    if seed is None:
        return SPLIT_UNKNOWN
    return _BY_SEED.get(int(seed), SPLIT_UNKNOWN)


def population_id(arity: int, seed, n: int | None = None) -> str:
    """The permanent, quotable name of a population.

    `a16/s0/n25` reads as: 16-gene grammar, seed 0, first 25 valid draws.
    Two banks with the same id are the same hulls; two with different ids are
    not comparable, whatever their seeds say.
    """
    if seed is None:
        return f"a{int(arity)}/sUNKNOWN" + (f"/n{int(n)}" if n else "")
    tail = f"/n{int(n)}" if n else ""
    return f"a{int(arity)}/s{int(seed)}{tail}"


def is_regenerable(arity: int) -> bool:
    """Can today's code reproduce this population at all?

    False for every 15-gene bank. A bank that cannot be regenerated may be
    read as HISTORY and must not be quoted as a current rate.
    """
    return int(arity) == current_arity()


def may_tune_on(seed) -> bool:
    """Development only. The fence in `tests/test_population_split.py`
    enforces the other direction: no artifact under `data/` may carry the
    validation or held-out seed."""
    return split_of_seed(seed) == SPLIT_DEV
