#!/usr/bin/env python
"""Generate the E5 findings block from the ledger. GATE E5.

A NUMBER LIVES IN EXACTLY ONE PLACE, and in E5 that place is
`data/e5_real_hulls.json`. The sixteen questions the E5 brief asks are all
numeric, so answering them in hand-written prose would create a second copy
that drifts the first time a hull is added -- the defect this repository
keeps finding, one floor up in the documentation.

So the answers are GENERATED, between markers, exactly as the README gate
table is. `tests/test_e5_real_hulls.py` re-runs this and fails if the block
in `docs/gates/E5.md` has drifted from what the ledger actually says.

    python scripts/e5_report.py            # print
    python scripts/e5_report.py --write    # rewrite the block in E5.md
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from benchmarks import e5_sources                                # noqa: E402

DOC = ROOT / "docs" / "gates" / "E5.md"
LEDGER = ROOT / "data" / "e5_real_hulls.json"
FIX = ROOT / "tests" / "e5_real_hulls"
BEGIN = "<!-- E5-REPORT BEGIN — generated by scripts/e5_report.py -->"
END = "<!-- E5-REPORT END -->"

#: What counts as a PASS of the scalar round-trip, per gene, absolute.
#: Mirrors tests/test_e5_real_hulls.py::SCALAR_TOL, which is the enforcing
#: copy; this module reads it from there rather than restating it.


def _tols() -> dict:
    """The enforcing copy of the bars lives in the TEST, and is read from
    there rather than restated here -- a threshold written twice is the
    defect this repository keeps finding."""
    import tests.test_e5_real_hulls as t
    return {**{k: f"{v:g} rel" for k, v in t.SCALAR_TOL_REL.items()},
            **{k: f"{v:g} abs" for k, v in t.SCALAR_TOL_ABS.items()}}


def _subseries() -> dict:
    """DSYHS sub-series per hull, from the extraction survey."""
    p = ROOT / "data" / "e5_dsyhs_survey.json"
    if not p.exists():
        return {}
    s = json.loads(p.read_text())
    return {f"dsyhs_{int(k):02d}": v.get("series")
            for k, v in s.items() if v.get("status") == "ok"}


def build() -> str:
    rows = json.loads(LEDGER.read_text())
    tol = _tols()
    sub = _subseries()
    n = len(rows)
    complete = [r for r in rows if r["complete_six"]]
    partial = [r for r in rows if not r["complete_six"]]
    fams = sorted({r["source_family"] for r in rows})
    with_offsets = [r for r in rows
                    if (FIX / r["hull_id"] / "source_offsets.csv").exists()]

    # Parent geometries: a systematic series varies ONE parent. DSYHS
    # sub-series each have their own; Series 60 and Wigley are one apiece.
    dsy_subs = sorted({v for k, v in sub.items() if v is not None})
    parents = len(dsy_subs) + len([f for f in fams if "Delft" not in f])

    def dev(r, key):
        d = json.loads((FIX / r["hull_id"] / "residuals.json").read_text())
        return d["scalar_absolute"].get(key)

    import tests.test_e5_real_hulls as _t
    key = {"LWL": "LWL_m", "BWL": "BWL_m", "T": "T_m", "D": "D_m"}
    scal_pass, scal_fail = [], []
    for r in rows:
        d = json.loads((FIX / r["hull_id"] / "residuals.json").read_text())
        bad = []
        for k, v in d["scalar_absolute"].items():
            bar = (_t.SCALAR_TOL_REL[k] * abs(r[key[k]]) if k in key
                   else _t.SCALAR_TOL_ABS[k])
            if abs(v) > bar:
                bad.append(k)
        (scal_fail if bad else scal_pass).append((r["hull_id"], bad))

    g = np.array([r["geom_rms_pct_halfbeam"] for r in rows])
    worst = sorted(rows, key=lambda r: -r["geom_rms_pct_halfbeam"])[:5]
    best = sorted(rows, key=lambda r: r["geom_rms_pct_halfbeam"])[:3]

    lwl = np.array([r["LWL_m"] for r in rows])
    cp = np.array([r["Cp"] for r in rows])
    lcb = np.array([r["LCB_percent"] for r in rows])
    rb = [r for r in rows if r["hard_chine_or_round_bilge"] == "round_bilge"]
    hc = [r for r in rows if r["hard_chine_or_round_bilge"] == "hard_chine"]
    inr = [r for r in rows if r["range_class"] == "IN_RANGE"]

    L = []
    a = L.append
    a(BEGIN)
    a("")
    a("## The sixteen questions")
    a("")
    a("| # | question | answer |")
    a("|---|---|---|")
    a(f"| 1 | How many real hulls were found? | **{n}** |")
    a(f"| 2 | How many have actual published offsets? | **{len(with_offsets)}**"
      f" — every hull in the corpus; a hull without geometry is not admitted |")
    a(f"| 3 | How many have all six required parameters? | **{len(complete)}**"
      f" complete, {len(partial)} partial (no published depth) |")
    a(f"| 4 | How many have independent lines geometry? | **{len(with_offsets)}**"
      f" — offsets extracted from published geometry, never from the kernel |")
    a(f"| 5 | How many independent source families? | **{len(fams)}** — "
      f"{', '.join(fams)} |")
    a(f"| 6 | How many independent parent geometries? | **{parents}** — "
      f"{len(dsy_subs)} DSYHS sub-series parents plus one each for the "
      f"other families |")
    a(f"| 7 | Minimum / maximum LWL | **{lwl.min():.3f} m / {lwl.max():.3f} m** |")
    a(f"| 8 | Minimum / maximum Cp | **{cp.min():.4f} / {cp.max():.4f}** |")
    a(f"| 9 | Minimum / maximum LCB | **{lcb.min():+.3f}% / {lcb.max():+.3f}%** "
      f"of LWL, positive forward |")
    a(f"| 10 | How many round bilge? | **{len(rb)}** |")
    a(f"| 11 | How many hard chine? | **{len(hc)}** |")
    a(f"| 12 | Scalar round-trip pass rate | **{100 * len(scal_pass) / n:.1f}%**"
      f" ({len(scal_pass)}/{n}) |")
    a(f"| 13 | Geometric round-trip | reported for **{n}/{n}**; RMS offset "
      f"error median **{np.median(g):.2f}%** of half-beam, worst "
      f"**{g.max():.2f}%** |")
    a(f"| 14 | Worst residuals | " +
      "; ".join(f"{r['hull_id']} {r['geom_rms_pct_halfbeam']:.2f}%"
                for r in worst) + " |")
    a(f"| 15 | Which hull fails, and why? | see the two lists below |")
    a(f"| 16 | Source, parameterisation or kernel? | see *Where the error "
      f"lives* below |")
    a("")
    a("### Independence, counted three ways")
    a("")
    a("Reporting only the first of these is the inflation this gate exists "
      "to prevent.")
    a("")
    a(f"- **{n} hull instances**")
    a(f"- **{len(fams)} independent source families**")
    a(f"- **{parents} independent parent geometries**")
    a("")
    a("### Range classification")
    a("")
    a("| class | count | meaning |")
    a("|---|---|---|")
    a(f"| IN_RANGE | {len(inr)} | every one of the six lies inside the "
      f"genome's own box |")
    for cls in ("NEAR_RANGE", "OUT_OF_RANGE"):
        m = [r for r in rows if r["range_class"] == cls]
        if m:
            a(f"| {cls} | {len(m)} | " +
              "; ".join(f"{r['hull_id']}: {r['range_note']}" for r in m[:3])
              + " |")
    a("")
    a("### Scalar round-trip")
    a("")
    if scal_fail:
        a("Hulls outside tolerance:")
        a("")
        for hid, bad in scal_fail:
            a(f"- `{hid}` — {', '.join(bad)}")
    else:
        a(f"All **{n}** hulls return every pinned parameter inside "
          f"tolerance. Largest deviations observed across the corpus:")
        a("")
        a("| gene | worst deviation (relative for LWL/BWL/T/D) | bar |")
        a("|---|---|---|")
        for k in ("LWL", "BWL", "T", "D", "Cp", "lcb"):
            vals = [abs(dev(r, k)) / (abs(r[key[k]]) if k in key else 1.0)
                    for r in rows if dev(r, k) is not None]
            if vals:
                a(f"| {k} | {max(vals):.3e} | {tol[k]} |")
    a("")
    a("### Geometric round-trip — the number that matters")
    a("")
    a("RMS offset error between the generated hull and the source's own "
      "offsets, with the six PINNED at the source values and only the ten "
      "shape genes fitted. As a percentage of the source half-beam.")
    a("")
    a("| | RMS % of half-beam |")
    a("|---|---|")
    a(f"| best | {g.min():.2f} (`{best[0]['hull_id']}`) |")
    a(f"| median | {np.median(g):.2f} |")
    a(f"| mean | {g.mean():.2f} |")
    a(f"| worst | {g.max():.2f} (`{worst[0]['hull_id']}`) |")
    a("")
    a("Per family:")
    a("")
    a("| family | hulls | median RMS % half-beam | worst |")
    a("|---|---|---|---|")
    for f in fams:
        m = np.array([r["geom_rms_pct_halfbeam"] for r in rows
                      if r["source_family"] == f])
        a(f"| {f} | {len(m)} | {np.median(m):.2f} | {m.max():.2f} |")
    a("")
    a(END)
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    block = build()
    if not a.write:
        print(block)
        return 0
    doc = DOC.read_text()
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < 0:
        raise SystemExit(f"{DOC} has no E5-REPORT markers")
    DOC.write_text(doc[:i] + block + doc[j + len(END):])
    print(f"wrote the generated block into {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
